PUT /api/cliente/20?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1
Host: localhost:8000
Cookie: XDEBUG_SESSION=PHPSTORM
Content-Length: 126
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

José
----WebKitFormBoundary7MA4YWxkTrZu0gW
